version: 2
jobs:
  build:
    docker:
    - image: cimg/go:1.17
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
        version: 20.10.14
        docker_layer_caching: true

    # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t kathywan/log4shell-vulnerable-app:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push kathywan/log4shell-vulnerable-app:$TAG