orbs:
  docker: circleci/docker@1.7.0
  lacework: lacework/lacework@1.5.0
version: 2.1
jobs:
  docker-job:
    docker:
      - image: cimg/base:stable
    steps:
      - docker/build:
          image: kathywan/log4shell-vulnerable-app
          dockerfile: $CIRCLE_WORKING_DIRECTO/DockerfileRY 
          debug: false 
          lint-dockerfile: false 
          treat-warnings-as-errors: false 
          tag: '0.1.$CIRCLE_BUILD_NUM' 
      - lacework/install-inline-scanner
      - lacework/inline-scanner-evaluate:
          image_name: kathywan/log4shell-vulnerable-app
          image_tag: '0.1.$CIRCLE_BUILD_NUM'
          save: true
          scan_library_packages: true
      - docker/push:
          image: kathywan/log4shell-vulnerable-app 
          tag: '0.1.$CIRCLE_BUILD_NUM' 

workflows:
  docker-workflow:
    jobs:
      - docker-job