orbs:
  docker: circleci/docker@2.1.0
  lacework: lacework/lacework@1.5.0
version: 2.1
jobs:
  docker-job:
    executor: docker/machine
    steps:
      - checkout
      - docker/install-docker
      - docker/build:
          image: kathywan/log4shell-vulnerable-app
          tag: '0.1.$CIRCLE_BUILD_NUM'
      - lacework/install-inline-scanner
      - lacework/inline-scanner-evaluate:
          image_name: kathywan/log4shell-vulnerable-app
          image_tag: '0.1.$CIRCLE_BUILD_NUM'
          save: true
          scan_library_packages: true
          policy: true
          critical_violation_exit_code: 2
          high_violation_exit_code: 3
          medium_violation_exit_code: 4
          low_violation_exit_code: 5
          info_violation_exit_code: 6
      - docker/push:
          image: kathywan/log4shell-vulnerable-app 
          tag: '0.1.$CIRCLE_BUILD_NUM' 
          
workflows:
  docker-workflow:
    jobs:
      - docker-job
