orbs:
  docker: circleci/docker@1.7.0
  lacework: lacework/lacework@1.5.0
version: 2.1
jobs:
  docker-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          image: kathywan/log4shell-vulnerable-app
          debug: false 
          lint-dockerfile: false 
          treat-warnings-as-errors: false 
          tag: '0.1.$CIRCLE_BUILD_NUM' 

      - lacework/inline-scanner-scan:
          image_name: lacework/lacework-inline-scanner
          image_tag: latest

      - docker/push:
          image: kathywan/log4shell-vulnerable-app 
          tag: '0.1.$CIRCLE_BUILD_NUM' 

workflows:
  docker-workflow:
    jobs:
      - docker-job