name: EKS deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: myEnv
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::950194951070:role/k8sAdmin

      - name: update kubeconfig
        uses: ItsKarma/aws-cli@v1.70.0
        env:
          EKS_CLUSTER: eksworkshop-eksctl
        with:
          args: eks update-kubeconfig --name $EKS_CLUSTER 

      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        with:
          args: apply .kubernetes/log4shell-vul-app-deploy.yaml
