name: EKS deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: myEnv
    
    steps:
      - uses: actions/checkout@v2
      
      - name: install awc cli and kubectl
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
          curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o kubectl
          chmod +x kubectl
          mkdir -p ~/.local/bin/kubectl
          mv ./kubectl ~/.local/bin/kubectl
          kubectl version
          
      - name: update kubeconfig
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
          AWS_ROLE_ARN: arn:aws:iam::950194951070:role/k8sAdmin
          EKS_CLUSTER: eksworkshop-eksctl
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER 

      - name: Trigger deploy
        run: |
          kubectl apply .kubernetes/log4shell-vul-app-deploy.yaml
